# Copyright (c) 2026 Robert Bosch GmbH
# SPDX-License-Identifier: AGPL-3.0

num_scenes: 10
checkpoint: "me-full"
gripper_id: 0
z0_id: 5 # -1 for no z0 conditioning
num_samples: 100

gripper: ["panda", "vx300", "dexee", "allegro", "shadow", "z0"]
gs: true
viz: false

defaults:
  - _self_
  - algorithm: flow
  - globals: default
  - model: kinematics_flow
