# Copyright (c) 2026 Robert Bosch GmbH
# SPDX-License-Identifier: AGPL-3.0

configuration:
  time_freq: 400.0
  dist_freq: 50.0
  position_scaling: ${algorithm.position_scaling}
  num_channels: 64
  num_mp_layer: [2, 3, 3]
  gripper: ${gripper}
  multiscale_channels: [32, 64, 64]
  multi_scale_tensor_field:
    blocks: 2
    num_scene_points: 10
    position_scaling: ${algorithm.position_scaling}
    time_freq: 400.0
    dist_freq: 50.0
    max_dist_length: 5.0
    num_channels: 64
    multiscale_channels: ${..multiscale_channels}
